patterns:
  r1:
    - "_1"
    - "_r1"
    - "_R1"
    - "_r"
    - "_F"
  r2:
    - "_2"
    - "_r2"
    - "_R2"
    - "_f"
    - "_R"
  ignore:
    - "^i_"
    - "^I_"
    - "_i\\d+"
    - "_I\\d+"
